coverage:
  notify:
    slack:
      default:
        url: secret:rBdwVitgcDNs0z43nJOC9TEhigADCyljpIFUVmldJkJCv6fMBEHXB9ZkcsCg0qCdMaISiR0QCG3GHQXHiTjMEpel7326q9czh5WToFBX1bauuwO2Du9WHZwlh1yWbN/JWcOB/Jv3SGb/fYl/cXeKM+5PRl+MjpOWZxBjYYPvyIo=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null